// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StorageApi.Migrations
{
    [DbContext(typeof(StorageApiContext))]
    [Migration("20260608122438_SeedProducts")]
    partial class SeedProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StorageApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<string>("Shelf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Verktyg",
                            Count = 20,
                            Description = "Standardhammare 500g",
                            Name = "Hammare",
                            Price = 149,
                            Shelf = "A1"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Verktyg",
                            Count = 35,
                            Description = "Platt skruvmejsel 6mm",
                            Name = "Skruvmejsel",
                            Price = 59,
                            Shelf = "A2"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Verktyg",
                            Count = 15,
                            Description = "Justerbar skiftnyckel 250mm",
                            Name = "Skiftnyckel",
                            Price = 199,
                            Shelf = "A3"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Bygg",
                            Count = 50,
                            Description = "Spackelspade i rostfritt stål",
                            Name = "Spackelputs",
                            Price = 89,
                            Shelf = "B1"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Bygg",
                            Count = 100,
                            Description = "Pensel 50mm för inomhusmålning",
                            Name = "Målarpensel",
                            Price = 39,
                            Shelf = "B2"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
